parameters:
  - name: dotNetVersion
    type: string
    default: '9.x'
  - name: buildConfiguration
    type: string
    default: 'Release'
  - name: projectPath
    type: string
    default: ''
  - name: runTests
    type: boolean
    default: true
  - name: unitTestProjectPath
    type: string
    default: ''
  - name: integrationTestProjectPath
    type: string
    default: ''
  - name: poolName
    type: string
    default: 'Default'


stages:
  - stage: BuildAndPublish
    displayName: 'Build and Publish'
    jobs:
      - job: Build
        pool:
          name: ${{ parameters.poolName }}
        steps:
          - task: UseDotNet@2
            displayName: 'install .NET SDK ${{ parameters.dotNetVersion }}'
            inputs:
              packageType: 'sdk'
              version: ${{ parameters.dotNetVersion }}
          - script: 
                dotnet restore $(Build.SourcesDirectory)/${{ parameters.projectPath }}
            displayName: 'Restore dependencies'
          - script: 
                dotnet build $(Build.SourcesDirectory)/${{ parameters.projectPath }} --configuration ${{ parameters.buildConfiguration }} --no-restore
            displayName: 'Build project'

          - ${{if eq(parameters.runTests, true)}}:
            - task: DotNetCoreCLI@2
              displayName: 'Run unit tests'
              inputs:
                command: 'test'
                projects: '$(Build.SourcesDirectory)/${{ parameters.unitTestProjectPath }}/ProductManagement.Tests.Unit.csproj'
                arguments: '--configuration ${{ parameters.buildConfiguration }} --logger trx --blame-crash'
                publishTestResults: true
                workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.unitTestProjectPath }}'
            - task: DotNetCoreCLI@2
              displayName: 'Run integration tests'
              condition: succeededOrFailed()
              inputs:
                command: 'test'
                projects: '$(Build.SourcesDirectory)/${{ parameters.integrationTestProjectPath }}/ProductManagement.Tests.Integration.csproj'
                arguments: '--configuration ${{ parameters.buildConfiguration }} --logger trx --blame-crash'
                publishTestResults: true
                workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.integrationTestProjectPath }}'  

            - task: publishTestResults@2
              displayName: 'Publish Test Results'
              inputs:
                testResultsFormat: 'VSTest'
                testResultsFiles: '**/*.trx'
            - task: docker@2
              displayName: 'Stop and remove existing testcontainer'
              condition: always()
              continueOnError: true
              inputs:
                command: 'custom'
                customCommand: 'ps -a --filter "label=org.testcontainer=true" --format "{{.ID}}" | xargs -r docker stop | xargs -r docker rm'


          - script: 
                dotnet publish $(Build.SourcesDirectory)/${{ parameters.projectPath }} --configuration ${{ parameters.buildConfiguration }} --no-build --output $(Build.ArtifactStagingDirectory)/app
            displayName: 'Publish project'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: "production-deployment-package"
              publishLocation: "Container"     
           


            

